meta_product_name: "Akord"
meta_title: "Akord | Simply get together"
meta_description: "The best app to create events and Akord for a date between your relatives"
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
